### ISSUE TITLE
Readability of PDF exported

### ISSUE THREAD

**Issue by Ideal-Li** [ArtexJay/Obsidian-CyberGlow#21] opened 2022-10-24 20:53 UTC
After exported to PDF, the presentation of "- " , "---"  and content within " `` " becomes less reader friendly.

**Comment by ArtexJay** [comment] 2022-10-26 23:39
Could you upload a screenshot of how it looks for you? 
Be sure that your PDF is not in night mode, this tends reverse sometimes unsuccessfully the colors in the PDF.

In PDF this is how it should look at the moment.
![image](https://user-images.githubusercontent.com/32932497/198158457-f98feaad-5fc0-4ce6-ab9c-dbabbec9e0cd.png)

**Comment by Ideal-Li** [comment] 2022-10-27 13:31
Hi Emperor:

Thanks for your reply. I did not expect that you would reply my message.
As I really like your design very much (no other themes highlight outlines
as well as yours does), I left you the message the other day to try my
luck. But I really did not expect that you would help fix this up. Thank
you very much!!!

The screenshot is from my obsidian interface, which looks really nice,
right (thanks to your genius design), but the pdf attached looks quite
different. Maybe it's just my device's problem? Anyway, thank you very
much!!!!


[image: image.png]


Best Regards

Ideal

**Comment by Ideal-Li** [comment] 2022-10-27 13:38
This is how it looks in obsidian interface:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/23702029/198299712-20948dad-5e8d-4854-a331-b76200c66091.png">

And this is how the pdf looks like:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/23702029/198299795-55eddfbd-79ea-4778-8042-e778d0608eb5.png">

**Comment by ArtexJay** [comment] 2022-10-27 16:37
I am unable to reproduce this unfortunately. I tried to do the exact same layout you showed in your example. PDF for me exports without any of those graphical issues.
![image](https://user-images.githubusercontent.com/32932497/198347954-c32702a8-0a42-4ab4-8563-75bb6a03c914.png)

Ensure that you have the latest version of the theme and obsidian.

**Comment by ArtexJay** [comment] 2023-01-14 01:48
Will be closing this issue for now, until there is an update from the OP or another user sees the same issue.

**Closed by ArtexJay** 2023-01-14 01:48 UTC
Labels: Unable to Replicate
